### PR TITLE
Update Transifex Working Group Languages 

### PR DESCRIPTION
**Pull request by DeimerM**
This pull request updates the Transifex working group languages to include:

- Italian (Italy)
- Portuguese (Portugal)
- German (Germany)

Note: This pull request is an update to PR https://github.com/openedx/frontend-app-program-console/pull/98 as the original PR is no longer maintained.

@e0d @chennighan2u

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DeimerM! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @DeimerM! Just flagging that the branch conflicts will need to be resolved before reviewing. Thanks!

**Comment by DeimerM** [comment]
Hi @mphilbrick211! I hope you are doing great!! Thanks so much for your quick response!  In light of the translation approach changing with the merged PR yesterday https://github.com/openedx/frontend-app-program-console/pull/142 I'm going to close this PR. Would you mind helping me close this one https://github.com/openedx/frontend-app-program-console/pull/98?

Thanks again!

**Comment by openedx-webhooks** [comment]
@DeimerM Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-program-console&entry.867055334=https://github.com/openedx/frontend-app-program-console/pull/173&entry.1484655318=https://github.com/DeimerM&entry.752974735=2024-03-18+00:37&entry.1917517419=2024-03-19+23:28&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
