### PR TITLE
Reduce SCSS

### PR DESCRIPTION
**Pull request by Cup0fCoffee**
## Description

Reduces the amount of SCSS in the repo, by applying the styling using bootstrap classes wherever possible.

`Private-ref:` [BB-6216](https://tasks.opencraft.com/browse/BB-6216)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Cup0fCoffee!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@Cup0fCoffee Thank you for your contribution. Is this ready for our review?

**Comment by Cup0fCoffee** [comment]
@natabene Not yet, I'm waiting for @xitij2000 to review these changes first. I'll let you know once the PR is ready.

**Review by xitij2000 — APPROVED** [review]
:+1: Looks good!

I have one nit though, which is to reduce the duplication here. You can create two variables called `rowClasses` and `buttonClasses` and then reuse them instead of duplicating the code. 

- [x] I tested this: partial testing on devstack
- [x] I read through the code

**Comment by Cup0fCoffee** [comment]
> I have one nit though, which is to reduce the duplication here. You can create two variables called `rowClasses` and `buttonClasses` and then reuse them instead of duplicating the code.

Done :+1:

**Comment by Cup0fCoffee** [comment]
@natabene This PR is ready for your review.

**Comment by Cup0fCoffee** [comment]
@natabene Kind reminder that the PR is ready for review.

**Comment by natabene** [comment]
@Cup0fCoffee Thanks, it looks like team doesn't have bandwidth yet. Is there a deadline by which you are trying to get this merged?

**Comment by Cup0fCoffee** [comment]
@natabene Oh, I didn't see any acknowledgment, so I was worried that my initial ping was missed by accident. There is no rush. Sorry for the noise!

**Comment by ashultz0** [comment]
@Cup0fCoffee it's taken a while but I'm on getting this merged - would you please rebase and push or otherwise merge changes? I'm not actually super concerned about the changes except that the latest diff has not had a passing build and won't let me rerun, so while we're getting that green check might as well get base off the latest.

Thanks!

**Comment by Cup0fCoffee** [comment]
@ashultz0 I've rebased and force pushed. FYI, I might be unavailable until Monday, I hope it doesn't cause any inconvenience. Thanks!

**Comment by ashultz0** [comment]
@Cup0fCoffee thanks! Hopefully what happens is the checks pass and I merge it and on Monday you come back to see it closed up. :)

**Comment by ashultz0** [comment]
I had to do a lot of package updates to get this working again with current header and footer and so on which brings this branch out of date. I made a rebased copy branch to revalidate the check https://github.com/openedx/frontend-app-program-console/pull/75 and it's OK so moving ahead to merge this

**Comment by openedx-webhooks** [comment]
@Cup0fCoffee 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-program-console&entry.867055334=https://github.com/openedx/frontend-app-program-console/pull/58&entry.1484655318=https://github.com/Cup0fCoffee&entry.752974735=2022-08-16+14:03&entry.1917517419=2022-11-17+15:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
